
import static javax.security.auth.callback.ConfirmationCallback.NO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Thinkpad
 */
public class java2 extends javax.swing.JFrame {

    /**
     * Creates new form java2
     */
    public java2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eNIM = new javax.swing.JTextField();
        eNAMA = new javax.swing.JTextField();
        eCLEAR = new javax.swing.JButton();
        eEXIT = new javax.swing.JButton();
        eTampilOptionpane = new javax.swing.JButton();
        eTampilanLabel = new javax.swing.JButton();
        eAlamat = new javax.swing.JLabel();
        eNotmor = new javax.swing.JLabel();
        eAlamatt = new javax.swing.JTextField();
        eTelp = new javax.swing.JTextField();
        LabelOutputNim = new javax.swing.JLabel();
        LabelOutputNama = new javax.swing.JLabel();
        LabelOutputALAMAT = new javax.swing.JLabel();
        LabelOutputNOTELP = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        jLabel2.setText("NAMA");

        eNAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNAMAActionPerformed(evt);
            }
        });

        eCLEAR.setText("CLEAR");
        eCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCLEARActionPerformed(evt);
            }
        });

        eEXIT.setText("EXIT");
        eEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEXITActionPerformed(evt);
            }
        });

        eTampilOptionpane.setText("TampilOptionpane");
        eTampilOptionpane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTampilOptionpaneActionPerformed(evt);
            }
        });

        eTampilanLabel.setText("TampilanLabel");
        eTampilanLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTampilanLabelActionPerformed(evt);
            }
        });

        eAlamat.setText("ALAMAT");

        eNotmor.setText("NO TELPON");

        eAlamatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAlamattActionPerformed(evt);
            }
        });

        eTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTelpActionPerformed(evt);
            }
        });

        LabelOutputNim.setText("NIM");

        LabelOutputNama.setText("NAMA");

        LabelOutputALAMAT.setText("ALAMAT");

        LabelOutputNOTELP.setText("NOTELP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eTampilOptionpane)
                            .addComponent(eTampilanLabel))
                        .addGap(53, 53, 53)
                        .addComponent(LabelOutputNim)
                        .addGap(71, 71, 71)
                        .addComponent(LabelOutputNama))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(eCLEAR))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eAlamat)
                                    .addComponent(eNotmor))))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelOutputALAMAT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelOutputNOTELP))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(eEXIT)
                                .addComponent(eNAMA)
                                .addComponent(eNIM)
                                .addComponent(eAlamatt)
                                .addComponent(eTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eAlamat)
                    .addComponent(eAlamatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNotmor)
                    .addComponent(eTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCLEAR)
                    .addComponent(eEXIT))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTampilOptionpane)
                    .addComponent(LabelOutputNim)
                    .addComponent(LabelOutputNama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTampilanLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelOutputALAMAT)
                        .addComponent(LabelOutputNOTELP)))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eNAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNAMAActionPerformed

    private void eEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEXITActionPerformed
        System.exit(0);

    }//GEN-LAST:event_eEXITActionPerformed

    private void eCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCLEARActionPerformed
        eNIM.setText("");
        eNAMA.setText("");
        eAlamatt.setText("");
        eTelp.setText("");

    }//GEN-LAST:event_eCLEARActionPerformed

    private void eTampilOptionpaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTampilOptionpaneActionPerformed
        String NIM = eNIM.getText();
        String NAMA = eNAMA.getText();
        String ALAMAT = eAlamatt.getText();
        String NOTMOR = eTelp.getText();
         JOptionPane.showMessageDialog(null, "NIM Saya:"+NIM+"\n Nama Saya:"+NAMA+"\n Alamat Saya:"+ALAMAT+"\n Nomor Telepon Saya:"+NOTMOR, "Pesan", 
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_eTampilOptionpaneActionPerformed

    private void eTampilanLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTampilanLabelActionPerformed
           String NIM = eNIM.getText();
        String NAMA = eNAMA.getText();
        String ALAMAT = eAlamatt.getText();
        String NOTMOR = eTelp.getText();
        LabelOutputNim.setText(NIM);
        LabelOutputNama.setText(NAMA);
        LabelOutputALAMAT.setText(ALAMAT);
        LabelOutputNOTELP.setText(NOTMOR);
    }//GEN-LAST:event_eTampilanLabelActionPerformed

    private void eTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTelpActionPerformed

    private void eAlamattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAlamattActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eAlamattActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new java2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelOutputALAMAT;
    private javax.swing.JLabel LabelOutputNOTELP;
    private javax.swing.JLabel LabelOutputNama;
    private javax.swing.JLabel LabelOutputNim;
    private javax.swing.JLabel eAlamat;
    private javax.swing.JTextField eAlamatt;
    private javax.swing.JButton eCLEAR;
    private javax.swing.JButton eEXIT;
    private javax.swing.JTextField eNAMA;
    private javax.swing.JTextField eNIM;
    private javax.swing.JLabel eNotmor;
    private javax.swing.JButton eTampilOptionpane;
    private javax.swing.JButton eTampilanLabel;
    private javax.swing.JTextField eTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
